name: publish to nuget
on:
    push:
        branches:
            - main

jobs:
    publish:
        name: build, pack & publish
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Setup dotnet
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: 5.0.x

            # Publish
            - name: publish on version change
              id: publish_nuget
              uses: rohith/publish-nuget@v2
              with:
                  PROJECT_FILE_PATH: IPCSocketBridge.NET/IPCSocketBridge.NET.fsproj
                  PACKAGE_NAME: IPCSocketBridge.NET
                  NUGET_KEY: ${{secrets.NUGET_API_KEY}}
